# Copy from kubespray
---
- name: haproxy for workers | Make haproxy directory
  file:
    path: "{{ haproxy_config_dir }}"
    state: directory
    mode: 0700
    owner: root

- name: haproxy for workers | Write haproxy configuration
  template:
    src: "loadbalancer/haproxy.cfg.j2"
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"
    owner: root
    mode: 0755
    backup: yes

- name: haproxy for workers | Get checksum from config
  stat:
    path: "{{ haproxy_config_dir }}/haproxy.cfg"
    get_attributes: no
    get_checksum: yes
    get_mime: no
  register: haproxy_stat

- name: haproxy for workers | Write static pod
  template:
    src: manifests/haproxy.manifest.j2
    dest: "{{ kube_manifest_dir }}/haproxy.yml"
