- hosts: all
  serial: 1   
  gather_facts: false
  become: yes
  vars:
  tasks:    
    - command: >
        cat /etc/kubernetes/admin.conf
      register:
          raw_config
      ignore_errors: true
    - set_fact:
        admin_cert: "{{ raw_config.stdout | from_yaml | json_query('[users][?name==\"kubernetes-admin\"] | [].user | [0].\"client-certificate-data\"') }}"
        admin_key: "{{ raw_config.stdout | from_yaml | json_query('[users][?name==\"kubernetes-admin\"] | [].user | [0].\"client-key-data\"') }}"
      when: "'FAILED' not in raw_config.stderr"
    - debug:
        msg: "{{admin_cert}}"
    - copy: 
        dest: admin_cert_file.ansible
        content: '{{ admin_cert | b64decode }}'
      with_items:
      - { dest: admin_cert_file.ansible, content: '{{ admin_cert | b64decode }}' }
      - { dest: admin_key_file.ansible, content: '{{ admin_key| b64decode }}' }
      when: "'FAILED' not in raw_config.stderr"
    - uri:
        follow_redirects: none
        validate_certs: false
        timeout: 5
        url: "https://{{ ansible_host }}:6443/"
        client_cert: admin_cert_file.ansible
        client_key: admin_key_file.ansible
      register: uri_data
      when: "'FAILED' not in raw_config.stderr"
