all:
  children:
    bastions:
    loadbalancers:
    masters:
      hosts:
        master-1:
          ansible_host: 192.168.10.151
          private_ip: 192.168.10.151
          public_ip: 192.168.10.151
        master-2:
          ansible_host: 192.168.10.152
          private_ip: 192.168.10.152
          public_ip: 192.168.10.152
        master-3:
          ansible_host: 192.168.10.153
          private_ip: 192.168.10.153
          public_ip: 192.168.10.153
    workers:
      hosts:
        worker-0:
          ansible_host: 192.168.10.141
          private_ip: 192.168.10.141
          public_ip: 192.168.10.141
  vars:
    api_loadbalancer_ip: 192.168.10.150
    api_loadbalancer_domain_name: "lb.k8s.cluster.local"
    ansible_user: user
