all:
  children:
    bastions:
    loadbalancers:
    masters:
      hosts:
        master1:
          ansible_host: 192.168.13.202
          private_ip: 192.168.13.202
          public_ip: 192.168.13.202
          first_master: true
    workers:
  vars:
    api_loadbalancer_ip: 
