all:
  children:
    bastions:
    ingress-loadbalancers:
      hosts:
        ingress-lb-1:
          ansible_host: 192.168.10.164
          private_ip: 192.168.10.164
          public_ip: 192.168.10.164
        ingress-lb-2:
          ansible_host: 192.168.10.165
          private_ip: 192.168.10.165
          public_ip: 192.168.10.165
    masters:
      hosts:
        master-1:
          ansible_host: 192.168.10.151
          private_ip: 192.168.10.151
          public_ip: 192.168.10.151
        master-2:
          ansible_host: 192.168.10.152
          private_ip: 192.168.10.152
          public_ip: 192.168.10.152
        master-3:
          ansible_host: 192.168.10.153
          private_ip: 192.168.10.153
          public_ip: 192.168.10.153
    workers:
      hosts:
        worker-0:
          ansible_host: 192.168.10.141
          private_ip: 192.168.10.141
          public_ip: 192.168.10.141
  vars:
    api_loadbalancer_ip: 192.168.10.150
    api_loadbalancer_domain_name: "lb.k8s.cluster.local"
    ingress_loadbalancer_float_ip: 192.168.10.160
    ansible_user: user
