---
# Copy from kubespray

- name: restart docker
  command: /bin/true
  notify:
    - Docker Install | reload docker
    - Docker Install | wait for docker
 
- name: restart containerd
  command: /bin/true
  notify:
    - Containerd Install | reload containerd
    - Containerd Install | wait for containerd

- name: restart crio
  command: /bin/true
  notify:
    - crio Install | reload crio
    - crio Install | wait for crio

- name: Docker Install | reload docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes
  become: yes
 
- name: Docker Install | wait for docker
  command: "docker images"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0
  become: yes

- name: Containerd Install | reload containerd
  service:
    name: containerd
    state: restarted
    daemon_reload: yes
  become: yes
 
- name: Containerd Install | wait for containerd
  command: "crictl images"
  register: containerd_ready
  retries: 20
  delay: 1
  until: containerd_ready.rc == 0
  become: yes

- name: crio Install | reload crio
  service:
    name: crio
    state: restarted
    daemon_reload: yes
  become: yes
 
- name: crio Install | wait for crio
  command: "crictl images"
  register: crio_ready
  retries: 20
  delay: 1
  until: crio_ready.rc == 0
  become: yes
