---
- name: Base Packages | Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Base Packages | Copy config file
  template:
    src: "{{ item.src }}"
    dest: "/etc/apt/apt.conf.d/{{ item.dest }}"
  with_items:
    - { src: 20auto-upgrades.j2, dest: 20auto-upgrades }
    - { src: 50unattended-upgrades.j2, dest: 50unattended-upgrades }

- name: Base Packages | Restart service
  systemd:
    name: unattended-upgrades
    state: restarted 

- name: Base Packages | Install base tools
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes

- name: Base Packages | Enable sysstat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED="true"
  when: '"sysstat" in packages'

