---
- name: Worker | Sysctl tuning for worker node
  sysctl:
    name: "{{ item.key }}"
    state: present
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_dict: "{{ sysctl_worker }}"
  become: true
