- name: Disable translation for apt
  file:
    src: 20translate
    dest: /etc/apt/apt.conf.d/20translate

- name: Add http proxy for apt
  template:
    src: 20proxy.j2
    dest: /etc/apt/apt.conf.d/20proxy
  when: http_proxy is defined

- name: Add Kubernete apt repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg.asc
    state: present

- name: Add Docker apt repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Kubernetes apt repository 
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Base Packages | Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Base Packages | Copy config file
  template:
    src: "{{ item.src }}"
    dest: /etc/apt/apt.conf.d/{{ item.dest }}
  with_items:
    - { src: 20auto-upgrades.j2, dest: 20auto-upgrades }
    - { src: 50unattended-upgrades.j2, dest: 50unattended-upgrades }

- name: Base Packages | Restart service
  systemd:
    name: unattended-upgrades
    state: restarted 

- name: Base Packages | Install base tools
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes

- name: Base Packages | Enable sysstat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED="true"
  when: '"sysstat" in packages'

