---
- name: Join Master | Generate CA certification hash
  shell: set -o pipefail && openssl x509 -pubkey -in {{ kube_cert_dir }}/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  args:
    executable: /bin/bash
  register: kubeadm_ca_hash
  delegate_to: "{{ groups['masters'][0] }}"

- name: Join Master | Set fact CA hash
  set_fact:
    ca_cert_hash: "{{ kubeadm_ca_hash.stdout }}"

- name: Join Master | Generate token
  command: kubeadm token create
  register: kubeadm_token
  retries: 5
  delay: 10
  until: kubeadm_token is not failed
  delegate_to: "{{ groups['masters'][0] }}"

- name: Join Master | Set fact for token
  set_fact:
    token: "{{ kubeadm_token.stdout }}"

#- name: Join Master | Generate certification key
#  command: kubeadm certs certificate-key
#  register: kubeadm_certification_key
#  delegate_to: "{{ groups['masters'][0] }}"

- name: Join Master | Set fact for certification key
  set_fact:
    kubeadm_certificate_key: "{{ hostvars[groups['masters'][0]]['kubeadm_certificate_key'] }}"

- name: Join Master | Create kubeadm join config file
  template:
    src: "kubeadm-join-master.yml.j2"
    dest: "/etc/kubernetes/kubeadm-join.yml"

- name: Join Master | Join to cluster 
  command: >-
    kubeadm join --config /etc/kubernetes/kubeadm-join.yml 
    --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests
