---
- import_tasks: first-master.yml
  become: yes
  when: inventory_hostname == groups['masters']|first

- import_tasks: join-master.yml
  become: true 
  when: 
    - inventory_hostname != groups['masters']|first
    - inventory_hostname in groups['masters']
