---
- import_tasks: worker/haproxy.yml
  when:
    - not is_kube_master
    - api_loadbalancer_worker == 'haproxy'
  tags:
    - haproxy

- import_tasks: master/haproxy-keepalived.yml
  become: yes
  when:
    - is_kube_master
    - api_loadbalancer_master == 'haproxy'
  tags:
    - haproxy
