# Cluster Configuration
kube_version: 1.22.4
kube_apt_version: "{{ kube_version }}-00"
container_runtime: "containerd"
container_runtime_socket: "{% if container_runtime == 'containerd' %}/var/run/containerd/containerd.sock{% elif container_runtime == 'crio' %}/var/run/crio/crio.sock{% endif %}"
kube_apiserver_port: 6443
loadbalancer_apiserver_port: 8443

kube_image_repo: "k8s.gcr.io"
docker_image_repo: "docker.io"
k8s_image_pull_policy: "IfNotPresent"

is_kube_master: "{{ inventory_hostname in groups['masters'] }}"

private_interface: "eth0"

kube_cert_dir: "/etc/kubernetes/pki"
kube_config_dir: "/etc/kubernetes"

# Network plugin
calico_image_repo: "{{ docker_image_repo }}/calico"
calico_version: "v3.19.1"
